version: '3.4'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./pg_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf","--daemonize","no"]
    volumes:
      - ./redis.conf.example:/usr/local/etc/redis/redis.conf
      - redis_data:/data

  harukamaaleoexplorer:
    image: harukamaaleoexplorer
    build:
      context: .
      dockerfile: ./alpine.Dockerfile
      #dockerfile: ./slim.Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=postgres
      - DB_SCHEMA=explorer
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - HOST=0.0.0.0
      - PORT=8800
      - API_PORT=8801
      - API_HOST=0.0.0.0
      - P2P_NODE_HOST=host.docker.internal
      - P2P_NODE_PORT=4133
      - P2P_BLOCK_BATCH_SIZE=1
      - RPC_URL_ROOT=http://host.docker.internal:3033
      - DEBUG=1
      - DEV_MODE=1
      - TURNSTILE_SITE_KEY=0x0
      - TURNSTILE_SECRET_KEY=0x0
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 8800:8800
      - 8801:8801

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
